---
version: "3.4"
services:
  explorer:
    build:
      context: .
      args:
        ENVIRONMENT: deployment
    ports:
      - 90:8080
    environment:
      # - DB_HOSTNAME=host.docker.internal
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
      - DB_PORT=5432
      - FLASK_ENV=development
      - FLASK_APP=cubedash
      - FLASK_DEBUG=1
      - CUBEDASH_DEFAULT_TIMEZONE=Australia/Darwin
      # - VIRTUAL_HOST=datacube.explorer
    #depends_on:
     # - postgres
networks:
 default:
  external:
   name: odcnet
